name: Build and Test

on: [push]

jobs:
  unit-test:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: swift build

    - name: Test
      run: swift test
